# Generated by Django 5.2.17 on 2026-08-22 23:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0003_auxcomm_and_incm_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("asset_id", models.CharField(max_length=80, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("radio", "Radio"),
                            ("battery", "Battery"),
                            ("antenna", "Antenna"),
                            ("cable", "Programming cable"),
                            ("microphone", "Microphone"),
                            ("accessory", "Other accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("serial_number", models.CharField(blank=True, max_length=160)),
                ("alias", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_service", "In service"),
                            ("spare", "Spare"),
                            ("checked_out", "Checked out"),
                            ("maintenance", "Maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="in_service",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_assets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_id"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("template_name", models.CharField(max_length=200)),
                ("template_version", models.CharField(blank=True, max_length=80)),
                ("programmed_at", models.DateTimeField()),
                ("codeplug_backup_saved", models.BooleanField()),
                ("backup_note", models.CharField(blank=True, max_length=300)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programming_records",
                        to="inventory.asset",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programming_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-programmed_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetCheckout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("assigned_name", models.CharField(max_length=200)),
                ("assigned_organization", models.CharField(max_length=200)),
                ("driver_license_jurisdiction", models.CharField(max_length=8)),
                ("driver_license_ciphertext", models.TextField()),
                ("driver_license_last_four", models.CharField(max_length=4)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("hold", "Accountability hold"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("checked_out_at", models.DateTimeField(auto_now_add=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "return_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Returned without damage"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost or not returned"),
                            ("disputed", "Disputed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hold_reason", models.TextField(blank=True)),
                ("hold_resolved_at", models.DateTimeField(blank=True, null=True)),
                ("hold_resolution_note", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="inventory.asset",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_checkouts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hold_resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_holds_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_checkouts",
                        to="incidents.incident",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_returns_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_out_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state__in", ["active", "hold"])),
                        fields=("asset",),
                        name="one_open_checkout_per_asset",
                    )
                ],
            },
        ),
    ]
