# Generated by Django 5.2.17 on 2026-08-23 01:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="acquisition_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_subtype",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="asset",
            name="flash_code",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_calibrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="subscriber_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="asset",
            name="system_ids",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="assignment_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="mailing_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="phone_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="point_of_contact",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ChargingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charging_records",
                        to="inventory.asset",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charging_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("inspection", "Inspection"),
                            ("calibration", "Calibration"),
                            ("repair", "Repair"),
                            ("preventive", "Preventive maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField()),
                ("technician", models.CharField(max_length=200)),
                ("notes", models.TextField()),
                ("return_to_service", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="inventory.asset",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
    ]
