# Generated by Django 5.2.16 on 2026-07-23 20:57

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.sites.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("plans", "0002_alter_assignment_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RadioSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "location",
                    apps.sites.fields.PortablePointField(
                        editable=False, geography=False, spatial_index=True, srid=4326
                    ),
                ),
                ("entered_coordinate", models.CharField(blank=True, max_length=240)),
                (
                    "coordinate_format",
                    models.CharField(
                        choices=[
                            ("map", "Map placement"),
                            ("decimal", "Decimal degrees"),
                            ("ddm", "Degrees decimal minutes"),
                            ("dms", "Degrees minutes seconds"),
                            ("mgrs", "USNG/MGRS"),
                            ("address", "Address provider"),
                        ],
                        default="decimal",
                        max_length=16,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("source_identity", models.CharField(blank=True, max_length=240)),
                ("source_retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radio_sites",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManualRing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ring_type",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("fringe", "Fringe / uncertain"),
                            ("coordination", "Coordination"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "radius_m",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2147483647),
                        ]
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rings",
                        to="sites.radiosite",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "ring_type", "radius_m"],
            },
        ),
        migrations.CreateModel(
            name="SiteAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("site_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_links",
                        to="plans.assignment",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_links",
                        to="sites.radiosite",
                    ),
                ),
            ],
            options={
                "ordering": ["assignment__position", "site__name"],
            },
        ),
        migrations.AddIndex(
            model_name="radiosite",
            index=models.Index(
                fields=["incident", "latitude", "longitude"], name="sites_radio_inciden_da56d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="radiosite",
            constraint=models.UniqueConstraint(
                fields=("incident", "name"), name="unique_radio_site_name_per_incident"
            ),
        ),
        migrations.AddConstraint(
            model_name="radiosite",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="radio_site_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="radiosite",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="radio_site_valid_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualring",
            constraint=models.UniqueConstraint(
                fields=("site", "ring_type", "radius_m"), name="unique_manual_ring"
            ),
        ),
        migrations.AddConstraint(
            model_name="siteassignment",
            constraint=models.UniqueConstraint(
                fields=("site", "assignment"), name="unique_site_assignment"
            ),
        ),
    ]
