# Generated by Django 5.2.16 on 2026-07-23 20:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("resources", "0002_alter_conventionalchannel_bandwidth_hz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("function", models.CharField(max_length=160)),
                ("channel_name", models.CharField(max_length=160)),
                ("assignment", models.CharField(blank=True, max_length=200)),
                ("resource_snapshot", models.JSONField(default=dict)),
                ("rx_frequency_hz", models.BigIntegerField(blank=True, null=True)),
                ("rx_squelch", models.CharField(blank=True, max_length=40)),
                ("tx_frequency_hz", models.BigIntegerField(blank=True, null=True)),
                ("tx_squelch", models.CharField(blank=True, max_length=40)),
                ("mode", models.CharField(blank=True, max_length=40)),
                ("remarks", models.TextField(blank=True)),
                (
                    "structured_note",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("remote_base", "Remote Base"),
                            ("link", "Link"),
                            ("patch", "Patch"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=160)),
                ("site_address", models.TextField(blank=True)),
                ("phone_numbers", models.CharField(blank=True, max_length=240)),
                ("contact_24_hour", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conventional_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="resources.conventionalchannel",
                    ),
                ),
                (
                    "trunked_talkgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="resources.trunkedtalkgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ICS205Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Incident Radio Communications Plan", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ics205_plans",
                        to="incidents.incident",
                    ),
                ),
                (
                    "operational_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ics205_plans",
                        to="incidents.operationalperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("prepared_by_name", models.CharField(blank=True, max_length=160)),
                ("prepared_by_position", models.CharField(blank=True, max_length=160)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_plan_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "copied_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="plans.planrevision",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_plan_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="plans.ics205plan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "-number"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("remote_base", "Remote Base"),
                            ("link", "Link"),
                            ("patch", "Patch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignments",
                    models.ManyToManyField(related_name="relationships", to="plans.assignment"),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships",
                        to="plans.planrevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="plans.planrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="ics205plan",
            constraint=models.UniqueConstraint(
                fields=("incident", "operational_period"), name="unique_ics205_incident_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="planrevision",
            constraint=models.UniqueConstraint(
                fields=("plan", "number"), name="unique_plan_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("revision", "position"), name="unique_assignment_revision_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conventional_channel__isnull", False),
                    ("trunked_talkgroup__isnull", False),
                    _negated=True,
                ),
                name="assignment_single_resource_type",
            ),
        ),
    ]
