# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0002_alter_assignment_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="collaboration_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="planrevision",
            name="collaboration_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
