# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0004_assignment_operating_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="contact_publication_purpose",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="assignment",
            name="published_contact_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
