# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_contact_publication_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="contact_publication_placement",
            field=models.CharField(
                choices=[
                    ("remarks", "Assignment remarks"),
                    ("special_instructions", "Plan-wide special instructions"),
                ],
                default="remarks",
                max_length=24,
            ),
        ),
    ]
