# Generated by Django 5.2.16 on 2026-07-28 17:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("plans", "0002_alter_assignment_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeconflictionAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rule_set_id", models.CharField(max_length=80)),
                ("rule_set_version", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("input_snapshot", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                ("result_snapshot", models.JSONField()),
                ("result_sha256", models.CharField(max_length=64)),
                ("warning_count", models.PositiveIntegerField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_deconfliction_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deconfliction_analyses",
                        to="plans.planrevision",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_deconfliction_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deconfliction_analyses",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["incident", "approved_revision", "created_at"],
                        name="deconf_inc_revision_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approved_at__isnull", True),
                                ("approved_by__isnull", True),
                                ("status", "draft"),
                            ),
                            models.Q(
                                ("approved_at__isnull", False),
                                ("approved_by__isnull", False),
                                ("status", "approved"),
                            ),
                            _connector="OR",
                        ),
                        name="deconfliction_approval_consistent",
                    )
                ],
            },
        ),
    ]
