# Generated by Django 5.2.16

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("plans", "0003_collaboration_versions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_mutation_id", models.UUIDField(unique=True)),
                ("device_id", models.UUIDField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("revision.update", "Update revision"),
                            ("assignment.create", "Create assignment"),
                            ("assignment.update", "Update assignment"),
                            ("assignment.delete", "Delete assignment"),
                            ("assignment.reorder", "Reorder assignments"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("section", models.CharField(default="ics205", max_length=80)),
                ("base_version", models.PositiveBigIntegerField()),
                ("resulting_version", models.PositiveBigIntegerField(blank=True, null=True)),
                ("affected_fields", models.JSONField(default=list)),
                ("proposed_snapshot", models.JSONField(default=dict)),
                ("current_snapshot", models.JSONField(default=dict)),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$",
                                "Enter a lowercase SHA-256 digest.",
                            )
                        ],
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("saved", "Saved"),
                            ("conflict", "Conflict"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=12,
                    ),
                ),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collaboration_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collaboration_changes",
                        to="incidents.incident",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collaboration_changes",
                        to="plans.planrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "revision", "created_at"],
                        name="collaborati_inciden_e5d456_idx",
                    ),
                    models.Index(
                        fields=["actor", "disposition", "created_at"],
                        name="collaborati_actor_i_949d91_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PresenceLease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.UUIDField()),
                ("section", models.CharField(default="ics205", max_length=80)),
                (
                    "mode",
                    models.CharField(
                        choices=[("viewing", "Viewing"), ("editing", "Editing")],
                        max_length=12,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_leases",
                        to="incidents.incident",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_leases",
                        to="plans.planrevision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_leases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["revision", "section", "user__username"],
                "indexes": [
                    models.Index(
                        fields=["incident", "revision", "expires_at"],
                        name="collaborati_inciden_afa33e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("revision", "user", "device_id", "section"),
                        name="unique_collaboration_presence_lease",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensitiveFieldRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_type", models.CharField(default="plan_assignment", max_length=40)),
                ("field_name", models.CharField(max_length=80)),
                (
                    "unauthorized_visibility",
                    models.CharField(
                        choices=[("omitted", "Omitted"), ("redacted", "Redacted")],
                        default="omitted",
                        max_length=12,
                    ),
                ),
                ("view_roles", models.JSONField(default=list)),
                ("edit_roles", models.JSONField(default=list)),
                ("log_reads", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_sensitive_field_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensitive_field_rules",
                        to="incidents.incident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_sensitive_field_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["incident", "resource_type", "field_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "resource_type", "field_name"),
                        name="unique_incident_sensitive_field_rule",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollaborationResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("discard", "Keep saved record"),
                            ("reapply", "Copy values into a new change"),
                            ("replace", "Intentionally replace current values"),
                        ],
                        max_length=12,
                    ),
                ),
                ("explanation", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conflict",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolution",
                        to="collaboration.collaborationchange",
                    ),
                ),
                (
                    "replacement_change",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_resolution",
                        to="collaboration.collaborationchange",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collaboration_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
