# Generated by Django 5.2.16

from django.db import migrations, models


def use_restricted_term(apps, schema_editor):
    SensitiveFieldRule = apps.get_model("collaboration", "SensitiveFieldRule")
    SensitiveFieldRule.objects.filter(unauthorized_visibility="redacted").update(
        unauthorized_visibility="restricted"
    )


def restore_redacted_term(apps, schema_editor):
    SensitiveFieldRule = apps.get_model("collaboration", "SensitiveFieldRule")
    SensitiveFieldRule.objects.filter(unauthorized_visibility="restricted").update(
        unauthorized_visibility="redacted"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presencelease",
            name="field_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="presencelease",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(use_restricted_term, restore_redacted_term),
        migrations.AlterField(
            model_name="sensitivefieldrule",
            name="unauthorized_visibility",
            field=models.CharField(
                choices=[
                    ("omitted", "Omitted"),
                    ("restricted", "Access restricted"),
                ],
                default="omitted",
                max_length=12,
            ),
        ),
    ]
