# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_local_contingency_accounts_and_roles"),
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("administrator", "Administrator"),
                    ("coml", "COML"),
                    ("comc", "COMC"),
                    ("comt", "COMT"),
                    ("auxcomm", "AUXCOMM"),
                    ("incm", "INCM"),
                    ("contributor", "Contributor"),
                    ("read_only", "Read-only"),
                ],
                max_length=24,
            ),
        ),
    ]
