# Generated by Django 5.2.16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="external_identity",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                ("external_subject", models.CharField(max_length=200)),
                ("civicrm_contact_id", models.CharField(max_length=80)),
                (
                    "eligibility",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("ineligible", "Ineligible"),
                            ("ambiguous", "Ambiguous"),
                            ("stale", "Stale"),
                            ("disabled", "Disabled"),
                        ],
                        default="ambiguous",
                        max_length=16,
                    ),
                ),
                (
                    "mapped_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("administrator", "Administrator"),
                            ("coml", "COML"),
                            ("comc", "COMC"),
                            ("comt", "COMT"),
                            ("contributor", "Contributor"),
                            ("read_only", "Read-only"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "attributes_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$",
                                "Enter a lowercase SHA-256 digest.",
                            )
                        ],
                    ),
                ),
                ("last_refreshed_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "eligibility", "valid_until"],
                        name="accounts_ex_provide_e4de26_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_subject"),
                        name="unique_external_identity_subject",
                    ),
                    models.UniqueConstraint(
                        fields=("provider", "civicrm_contact_id"),
                        name="unique_external_identity_civicrm_contact",
                    ),
                ],
            },
        ),
    ]
