# Generated by Django 5.2.16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

ROLE_CHOICES = [
    ("administrator", "Administrator"),
    ("coml", "COML"),
    ("comc", "COMC"),
    ("comt", "COMT"),
    ("auxcomm", "AUXCOMM"),
    ("incm", "INCM"),
    ("contributor", "Contributor"),
    ("read_only", "Read-only"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_externalidentity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userroleassignment",
            name="role",
            field=models.CharField(
                choices=ROLE_CHOICES,
                default="read_only",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="externalidentity",
            name="mapped_role",
            field=models.CharField(
                blank=True,
                choices=ROLE_CHOICES,
                max_length=24,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LocalContingencyAccount",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="local_contingency_account",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("must_change_password", models.BooleanField(default=True)),
                ("is_synthetic_hidden", models.BooleanField(default=False)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_local_contingency_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disabled_local_contingency_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["user__username"]},
        ),
    ]
