# Generated by Django 5.2.16 on 2026-07-28 21:04

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineMutationReceipt",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                ("actor_id_snapshot", models.PositiveBigIntegerField()),
                ("device_id", models.UUIDField()),
                ("operation", models.CharField(max_length=40)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("revision_id", models.UUIDField()),
                (
                    "previous_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "mutation_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("payload_snapshot", models.JSONField(default=dict)),
                ("base_updated_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at_client", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("conflict", "Conflict"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=12,
                    ),
                ),
                ("result", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["package", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="OfflineConflictResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("discard", "Discard local change"),
                            ("requeue", "Refresh and create a replacement change"),
                        ],
                        max_length=12,
                    ),
                ),
                ("explanation", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_conflict_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolution",
                        to="offline.offlinemutationreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflinePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("locked", "Locked"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("purged", "Purged"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("scope", models.JSONField(default=dict)),
                ("payload_snapshot", models.JSONField(default=dict)),
                ("manifest", models.JSONField(default=dict)),
                (
                    "manifest_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("revision_state", models.JSONField(default=dict)),
                ("last_sequence", models.PositiveIntegerField(default=0)),
                (
                    "last_chain_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_packages",
                        to="incidents.incident",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="offlinemutationreceipt",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mutation_receipts",
                to="offline.offlinepackage",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinepackage",
            index=models.Index(
                fields=["incident", "requested_by", "status"], name="offline_off_inciden_4a459b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinepackage",
            index=models.Index(fields=["expires_at"], name="offline_off_expires_8736da_idx"),
        ),
        migrations.AddConstraint(
            model_name="offlinemutationreceipt",
            constraint=models.UniqueConstraint(
                fields=("package", "sequence"), name="unique_offline_package_mutation_sequence"
            ),
        ),
    ]
