# Generated by Django 5.2.16 on 2026-07-29 00:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("plans", "0003_collaboration_versions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("extension_key", models.SlugField(max_length=120, unique=True)),
                ("extension_version", models.CharField(max_length=40)),
                ("contract_version", models.CharField(max_length=20)),
                ("manifest_snapshot", models.JSONField()),
                ("manifest_sha256", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installed_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["extension_key"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("extension_key", models.SlugField(max_length=120)),
                ("extension_version", models.CharField(max_length=40)),
                ("contract_version", models.CharField(max_length=20)),
                ("capability", models.SlugField(max_length=120)),
                (
                    "capability_kind",
                    models.CharField(
                        choices=[("tool", "Tool"), ("report", "Report")], max_length=12
                    ),
                ),
                ("input_snapshot", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                ("result_snapshot", models.JSONField(default=dict)),
                ("result_sha256", models.CharField(max_length=64)),
                (
                    "output_classification",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("decision_support", "Decision support"),
                            ("official", "Official"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("complete", "Complete"), ("failed", "Failed")], max_length=12
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extension_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extension_executions",
                        to="incidents.incident",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extension_executions",
                        to="plans.planrevision",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="extensions.extensioninstallation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["incident", "extension_key", "created_at"],
                        name="extension_inc_key_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("failure_code", ""),
                                ("failure_message", ""),
                                ("status", "complete"),
                            ),
                            ("status", "failed"),
                            _connector="OR",
                        ),
                        name="extension_execution_failure_consistent",
                    )
                ],
            },
        ),
    ]
