# Generated by Django 5.2.16 on 2026-08-21 21:35

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FccImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("asr", "Antenna Structure Registration"),
                            ("uls_private", "ULS private land mobile"),
                            ("uls_commercial", "ULS commercial land mobile"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "archive_kind",
                    models.CharField(
                        choices=[
                            ("complete", "Complete reconciliation"),
                            ("daily", "Daily transaction"),
                        ],
                        default="complete",
                        max_length=12,
                    ),
                ),
                ("archive_name", models.CharField(max_length=80)),
                ("source_url", models.URLField(max_length=500)),
                (
                    "content_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("parser_version", models.CharField(max_length=40)),
                ("retrieved_at", models.DateTimeField()),
                ("record_counts", models.JSONField(default=dict)),
                ("is_current", models.BooleanField(default=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="AntennaStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("registration_number", models.CharField(max_length=20)),
                ("unique_system_identifier", models.CharField(blank=True, max_length=24)),
                ("status_code", models.CharField(blank=True, max_length=8)),
                ("owner_name", models.CharField(blank=True, max_length=300)),
                ("owner_frn", models.CharField(blank=True, max_length=20)),
                ("structure_type", models.CharField(blank=True, max_length=40)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
                ),
                (
                    "structure_height_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "ground_elevation_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "overall_height_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "overall_height_amsl_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                ("faa_study_number", models.CharField(blank=True, max_length=80)),
                ("painting_lighting", models.CharField(blank=True, max_length=120)),
                ("construction_date", models.DateField(blank=True, null=True)),
                ("dismantlement_date", models.DateField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antenna_structures",
                        to="fcc_data.fccimportbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["registration_number"],
            },
        ),
        migrations.CreateModel(
            name="UlsLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("unique_system_identifier", models.CharField(max_length=24)),
                ("call_sign", models.CharField(max_length=20)),
                ("license_status", models.CharField(max_length=8)),
                ("radio_service_code", models.CharField(max_length=8)),
                ("applicant_type_code", models.CharField(blank=True, max_length=8)),
                ("selection_rule", models.CharField(max_length=40)),
                ("licensee_name", models.CharField(blank=True, max_length=300)),
                ("frn", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=8)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("grant_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                ("last_action_date", models.DateField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="fcc_data.fccimportbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["call_sign", "unique_system_identifier"],
            },
        ),
        migrations.CreateModel(
            name="UlsFrequency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("location_number", models.PositiveIntegerField()),
                ("antenna_number", models.PositiveIntegerField()),
                ("station_class_code", models.CharField(blank=True, max_length=12)),
                (
                    "frequency_hz",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000000000),
                        ]
                    ),
                ),
                (
                    "output_power_w",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
                ),
                (
                    "effective_radiated_power_w",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
                ),
                ("number_of_units", models.PositiveIntegerField(blank=True, null=True)),
                ("source_frequency_id", models.CharField(blank=True, max_length=24)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="frequencies",
                        to="fcc_data.ulslicense",
                    ),
                ),
            ],
            options={
                "ordering": ["license", "location_number", "antenna_number", "frequency_hz"],
            },
        ),
        migrations.CreateModel(
            name="UlsEmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("location_number", models.PositiveIntegerField()),
                ("antenna_number", models.PositiveIntegerField()),
                (
                    "frequency_hz",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000000000),
                        ]
                    ),
                ),
                ("emission_designator", models.CharField(max_length=40)),
                ("source_frequency_id", models.CharField(blank=True, max_length=24)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emissions",
                        to="fcc_data.ulslicense",
                    ),
                ),
            ],
            options={
                "ordering": ["license", "location_number", "antenna_number", "frequency_hz"],
            },
        ),
        migrations.CreateModel(
            name="UlsLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("location_number", models.PositiveIntegerField()),
                ("location_type_code", models.CharField(blank=True, max_length=8)),
                ("location_class_code", models.CharField(blank=True, max_length=8)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("county", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=8)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
                ),
                (
                    "ground_elevation_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                ("asr_registration_number", models.CharField(blank=True, max_length=20)),
                ("structure_type", models.CharField(blank=True, max_length=40)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="fcc_data.ulslicense",
                    ),
                ),
            ],
            options={
                "ordering": ["license", "location_number"],
            },
        ),
        migrations.AddIndex(
            model_name="fccimportbatch",
            index=models.Index(
                fields=["dataset", "is_current"], name="fcc_data_fc_dataset_2d43c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fccimportbatch",
            constraint=models.UniqueConstraint(
                fields=("dataset", "content_sha256"), name="unique_fcc_dataset_archive_digest"
            ),
        ),
        migrations.AddConstraint(
            model_name="antennastructure",
            constraint=models.UniqueConstraint(
                fields=("batch", "registration_number"), name="unique_asr_registration_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="antennastructure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="fcc_asr_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="antennastructure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="fcc_asr_valid_longitude",
            ),
        ),
        migrations.AddIndex(
            model_name="ulslicense",
            index=models.Index(fields=["call_sign"], name="fcc_data_ul_call_si_2ac4f9_idx"),
        ),
        migrations.AddIndex(
            model_name="ulslicense",
            index=models.Index(
                fields=["radio_service_code", "license_status"],
                name="fcc_data_ul_radio_s_c826a5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ulslicense",
            constraint=models.UniqueConstraint(
                fields=("batch", "unique_system_identifier"), name="unique_uls_license_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="ulsfrequency",
            constraint=models.UniqueConstraint(
                fields=(
                    "license",
                    "location_number",
                    "antenna_number",
                    "frequency_hz",
                    "station_class_code",
                    "source_frequency_id",
                ),
                name="unique_uls_frequency_license_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="ulsemission",
            constraint=models.UniqueConstraint(
                fields=(
                    "license",
                    "location_number",
                    "antenna_number",
                    "frequency_hz",
                    "emission_designator",
                    "source_frequency_id",
                ),
                name="unique_uls_emission_license_frequency",
            ),
        ),
        migrations.AddConstraint(
            model_name="ulslocation",
            constraint=models.UniqueConstraint(
                fields=("license", "location_number"), name="unique_uls_location_license"
            ),
        ),
        migrations.AddConstraint(
            model_name="ulslocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="fcc_uls_location_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="ulslocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="fcc_uls_location_valid_longitude",
            ),
        ),
    ]
