# Generated by Django 5.2.16 on 2026-07-22 20:39

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic fixture"),
                            ("cisa_nifog", "CISA NIFOG"),
                            ("cisa_auxfog", "CISA AUXFOG"),
                            ("cisa_state_fog", "CISA state or regional FOG"),
                            ("local", "Local controlled source"),
                            ("incident", "Incident-created source"),
                            ("other", "Other approved source"),
                        ],
                        max_length=24,
                    ),
                ),
                ("authoritative_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResourceRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.CharField(max_length=80)),
                ("released_on", models.DateField(blank=True, null=True)),
                (
                    "effective_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("effective", "Effective"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "content_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="resources.resourcesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("conventional_count", models.PositiveIntegerField()),
                ("talkgroup_count", models.PositiveIntegerField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_record",
                        to="resources.resourcerelease",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="TrunkedTalkgroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identifier", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("system_name", models.CharField(max_length=160)),
                (
                    "talkgroup_id",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(16777215)]
                    ),
                ),
                ("mode", models.CharField(blank=True, max_length=40)),
                ("restrictions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trunked_talkgroups",
                        to="resources.resourcerelease",
                    ),
                ),
            ],
            options={
                "ordering": ["system_name", "name", "identifier"],
            },
        ),
        migrations.CreateModel(
            name="ConventionalChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identifier", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("band", models.CharField(blank=True, max_length=40)),
                (
                    "rx_frequency_hz",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000000000),
                        ]
                    ),
                ),
                (
                    "tx_frequency_hz",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000000000),
                        ],
                    ),
                ),
                ("bandwidth_hz", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("analog_fm", "Analog FM"),
                            ("p25", "P25"),
                            ("dmr", "DMR"),
                            ("nxdn", "NXDN"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rx_squelch", models.CharField(blank=True, max_length=40)),
                ("tx_squelch", models.CharField(blank=True, max_length=40)),
                ("restrictions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conventional_channels",
                        to="resources.resourcerelease",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "identifier"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("release", "identifier"),
                        name="unique_conventional_identifier_release",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="resourcerelease",
            constraint=models.UniqueConstraint(
                fields=("source", "version"), name="unique_source_release_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="trunkedtalkgroup",
            constraint=models.UniqueConstraint(
                fields=("release", "identifier"), name="unique_talkgroup_identifier_release"
            ),
        ),
    ]
