# Generated by Django 5.2.16 on 2026-07-22 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conventionalchannel",
            name="bandwidth_hz",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(2147483647)],
            ),
        ),
    ]
