# Generated by Django 5.2.16 on 2026-07-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_alter_conventionalchannel_bandwidth_hz"),
    ]

    operations = [
        migrations.AddField(
            model_name="conventionalchannel",
            name="authorization",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="conventionalchannel",
            name="channel_use",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="conventionalchannel",
            name="eligibility",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="conventionalchannel",
            name="emission_designator",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="conventionalchannel",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="conventionalchannel",
            name="source_pages",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="conventionalchannel",
            name="source_section",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="resourcerelease",
            name="document_title",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="resourcerelease",
            name="permitted_use",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resourcerelease",
            name="publisher",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="resourcerelease",
            name="retrieved_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcerelease",
            name="transformation_method",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trunkedtalkgroup",
            name="authorization",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trunkedtalkgroup",
            name="eligibility",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trunkedtalkgroup",
            name="source_pages",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="trunkedtalkgroup",
            name="source_section",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
