# Generated by Django 5.2.16 on 2026-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0003_conventionalchannel_authorization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcesource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("synthetic", "Synthetic fixture"),
                    ("cisa_nifog", "CISA NIFOG"),
                    ("cisa_auxfog", "CISA AUXFOG"),
                    ("cisa_state_fog", "CISA state or regional FOG"),
                    ("radioreference", "RadioReference"),
                    ("local", "Local controlled source"),
                    ("incident", "Incident-created source"),
                    ("other", "Other approved source"),
                ],
                max_length=24,
            ),
        ),
    ]
