# Generated by Django 5.2.16 on 2026-07-27 23:07

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriberProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("portable", "Portable"),
                            ("mobile", "Mobile"),
                            ("fixed", "Fixed"),
                            ("configurable", "Configurable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_subscriber_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriber_profiles",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["incident", "name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriberProfileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "tx_frequency_hz",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000000000),
                        ],
                    ),
                ),
                (
                    "rx_frequency_hz",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000000000),
                        ],
                    ),
                ),
                (
                    "transmitter_power_w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10000000")),
                        ],
                    ),
                ),
                (
                    "effective_radiated_power_w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10000000")),
                        ],
                    ),
                ),
                (
                    "erp_source",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("entered", "Entered"),
                            ("calculated", "Calculated"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                (
                    "receiver_sensitivity_dbm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-300")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "antenna_model",
                    models.CharField(blank=True, default=None, max_length=200, null=True),
                ),
                (
                    "antenna_gain_db",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-200")),
                            django.core.validators.MaxValueValidator(Decimal("200")),
                        ],
                    ),
                ),
                (
                    "antenna_gain_reference",
                    models.CharField(
                        choices=[("unknown", "Unknown"), ("dbi", "dBi"), ("dbd", "dBd")],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                (
                    "feed_line_type",
                    models.CharField(blank=True, default=None, max_length=160, null=True),
                ),
                (
                    "feed_line_length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1000000")),
                        ],
                    ),
                ),
                (
                    "feed_line_loss_db",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1000")),
                        ],
                    ),
                ),
                (
                    "additional_system_loss_db",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1000")),
                        ],
                    ),
                ),
                (
                    "polarization",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("vertical", "Vertical"),
                            ("horizontal", "Horizontal"),
                            ("circular", "Circular"),
                            ("mixed", "Mixed"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                (
                    "frequency_band",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("vhf_low", "VHF low"),
                            ("vhf_high", "VHF high"),
                            ("uhf", "UHF"),
                            ("700", "700 MHz"),
                            ("800", "800 MHz"),
                            ("900", "900 MHz"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                (
                    "emission_designator",
                    models.CharField(blank=True, default=None, max_length=32, null=True),
                ),
                (
                    "emission_bandwidth_hz",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000000000),
                        ],
                    ),
                ),
                (
                    "mounting_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("handheld", "Handheld"),
                            ("vehicle", "Vehicle"),
                            ("structure", "Structure"),
                            ("tower", "Tower"),
                            ("mast", "Mast"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "antenna_center_agl_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                (
                    "antenna_center_amsl_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100000")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                (
                    "haat_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100000")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                (
                    "input_basis",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("recorded_fact", "Recorded fact"),
                            ("modeled_assumption", "Modeled assumption"),
                            ("mixed", "Mixed"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                ("erp_calculation_path", models.JSONField(blank=True, default=dict)),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                ("input_sha256", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_subscriber_profile_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_subscriber_profile_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="rf_analysis.subscriberprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["profile", "-number"],
            },
        ),
        migrations.CreateModel(
            name="RFAnalysisInputSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("input_snapshot", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_rf_analysis_input_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rf_analysis_input_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rf_analysis_input_snapshots",
                        to="incidents.incident",
                    ),
                ),
                (
                    "profile_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_input_snapshots",
                        to="rf_analysis.subscriberprofileversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriberprofile",
            index=models.Index(
                fields=["incident", "archived_at"], name="rf_profile_incident_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriberprofileversion",
            constraint=models.UniqueConstraint(
                fields=("profile", "number"), name="unique_subscriber_profile_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriberprofileversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True),
                        ("approved_by__isnull", True),
                        ("input_sha256", ""),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("approved_by__isnull", False),
                        ("status", "approved"),
                        models.Q(("input_sha256", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="rf_profile_version_approval_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="rfanalysisinputsnapshot",
            index=models.Index(
                fields=["incident", "archived_at"], name="rf_snap_incident_active_idx"
            ),
        ),
    ]
