# Generated by Django 5.2.16 on 2026-07-28 00:06

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("rf_analysis", "0001_initial"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElevationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query_sha256", models.CharField(db_index=True, max_length=64)),
                ("query_snapshot", models.JSONField()),
                ("provider", models.CharField(max_length=160)),
                ("dataset_product", models.CharField(max_length=240)),
                ("horizontal_crs", models.CharField(max_length=120)),
                ("vertical_crs", models.CharField(max_length=120)),
                ("target_vertical_crs", models.CharField(max_length=120)),
                (
                    "resolution_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1000000")),
                        ],
                    ),
                ),
                ("source_version", models.CharField(blank=True, max_length=160)),
                ("source_retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("license_terms_url", models.URLField(blank=True, max_length=500)),
                ("permitted_use", models.TextField()),
                ("coverage", models.JSONField(blank=True, default=dict)),
                ("source_content_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "acquisition_state",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("missing", "Missing"),
                            ("out_of_coverage", "Out of coverage"),
                        ],
                        max_length=24,
                    ),
                ),
                ("sample_snapshot", models.JSONField()),
                ("sample_sha256", models.CharField(max_length=64)),
                ("transformation", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("retrieved_at", models.DateTimeField()),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_elevation_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elevation_snapshots",
                        to="incidents.incident",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elevation_snapshots",
                        to="sites.radiosite",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HAATCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "calculation_state",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("method", models.CharField(max_length=80)),
                ("method_version", models.CharField(max_length=80)),
                (
                    "radial_count",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(360),
                        ]
                    ),
                ),
                (
                    "start_azimuth_deg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("359.999")),
                        ],
                    ),
                ),
                (
                    "sampling_interval_m",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                (
                    "inner_distance_m",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                (
                    "outer_distance_m",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                (
                    "rounding_m",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "antenna_agl_m",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                (
                    "site_elevation_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100000")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                (
                    "antenna_amsl_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100000")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                (
                    "average_terrain_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100000")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                (
                    "haat_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100000")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("excluded_sample_count", models.PositiveIntegerField(default=0)),
                ("algorithm_snapshot", models.JSONField()),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("result_snapshot", models.JSONField()),
                ("result_sha256", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_haat_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_haat_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "elevation_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="haat_calculations",
                        to="rf_analysis.elevationsnapshot",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="haat_calculations",
                        to="incidents.incident",
                    ),
                ),
                (
                    "profile_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="haat_calculations",
                        to="rf_analysis.subscriberprofileversion",
                    ),
                ),
                (
                    "rf_input_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="haat_calculations",
                        to="rf_analysis.rfanalysisinputsnapshot",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="haat_calculations",
                        to="sites.radiosite",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retries",
                        to="rf_analysis.haatcalculation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="elevationsnapshot",
            index=models.Index(
                fields=["incident", "site", "query_sha256"], name="rf_elev_cache_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="haatcalculation",
            index=models.Index(
                fields=["incident", "site", "status"], name="rf_haat_inc_site_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="haatcalculation",
            constraint=models.CheckConstraint(
                condition=models.Q(("outer_distance_m__gt", models.F("inner_distance_m"))),
                name="rf_haat_outer_gt_inner",
            ),
        ),
        migrations.AddConstraint(
            model_name="haatcalculation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True),
                        ("approved_by__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("approved_by__isnull", False),
                        ("status", "approved"),
                    ),
                    _connector="OR",
                ),
                name="rf_haat_approval_consistent",
            ),
        ),
    ]
