# Generated by Django 5.2.16 on 2026-07-28 04:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("rf_analysis", "0002_elevationsnapshot_haatcalculation_and_more"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageEstimate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "calculation_state",
                    models.CharField(
                        choices=[("complete", "Complete"), ("unsupported", "Unsupported")],
                        max_length=16,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("rural", "Rural"),
                            ("suburban", "Suburban"),
                            ("urban", "Urban"),
                            ("dense_urban", "Dense urban"),
                        ],
                        max_length=16,
                    ),
                ),
                ("band", models.CharField(max_length=32)),
                ("engine", models.CharField(max_length=120)),
                ("engine_version", models.CharField(max_length=80)),
                ("preset", models.CharField(max_length=80)),
                ("preset_version", models.CharField(max_length=80)),
                ("center_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("center_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("nominal_distance_m", models.PositiveIntegerField(blank=True, null=True)),
                ("conservative_distance_m", models.PositiveIntegerField(blank=True, null=True)),
                ("optimistic_distance_m", models.PositiveIntegerField(blank=True, null=True)),
                ("input_snapshot", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                ("model_snapshot", models.JSONField()),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("explanation", models.TextField()),
                ("result_snapshot", models.JSONField()),
                ("result_sha256", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_coverage_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_coverage_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "haat_calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_estimates",
                        to="rf_analysis.haatcalculation",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_estimates",
                        to="incidents.incident",
                    ),
                ),
                (
                    "rf_input_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_estimates",
                        to="rf_analysis.rfanalysisinputsnapshot",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_estimates",
                        to="sites.radiosite",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "site", "status"], name="rf_cov_inc_site_status_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approved_at__isnull", True),
                                ("approved_by__isnull", True),
                                ("status", "draft"),
                            ),
                            models.Q(
                                ("approved_at__isnull", False),
                                ("approved_by__isnull", False),
                                ("status", "approved"),
                            ),
                            _connector="OR",
                        ),
                        name="rf_cov_approval_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("calculation_state", "complete"),
                                ("conservative_distance_m__isnull", False),
                                ("nominal_distance_m__isnull", False),
                                ("optimistic_distance_m__isnull", False),
                            ),
                            models.Q(
                                ("calculation_state", "unsupported"),
                                ("conservative_distance_m__isnull", True),
                                ("nominal_distance_m__isnull", True),
                                ("optimistic_distance_m__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="rf_cov_distance_state_consistent",
                    ),
                ],
            },
        ),
    ]
