# Generated by Django 5.2.16 on 2026-07-28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("rf_analysis", "0003_coverageestimate"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriberprofile",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("portable", "Portable"),
                    ("mobile", "Mobile"),
                    ("fixed", "Fixed"),
                    ("cache", "Cache"),
                    ("gateway", "Gateway"),
                    ("configurable", "Configurable"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DirectionalCoverageAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "calculation_state",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("unsupported", "Unsupported"),
                            ("no_overlap", "No probable two-way overlap"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("rural", "Rural"),
                            ("suburban", "Suburban"),
                            ("urban", "Urban"),
                            ("dense_urban", "Dense urban"),
                        ],
                        max_length=16,
                    ),
                ),
                ("engine", models.CharField(max_length=120)),
                ("engine_version", models.CharField(max_length=80)),
                ("preset", models.CharField(max_length=80)),
                ("preset_version", models.CharField(max_length=80)),
                ("rule_version", models.CharField(max_length=80)),
                ("center_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("center_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("talk_out_distance_m", models.PositiveIntegerField(blank=True, null=True)),
                ("talk_in_distance_m", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "probable_two_way_distance_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "limiting_path",
                    models.CharField(
                        choices=[
                            ("talk_out", "Talk-out"),
                            ("talk_in", "Talk-in"),
                            ("equal", "Equal"),
                            ("none", "Not available"),
                        ],
                        max_length=12,
                    ),
                ),
                ("input_snapshot", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                ("model_snapshot", models.JSONField()),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("explanation", models.TextField()),
                ("result_snapshot", models.JSONField()),
                ("result_sha256", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_directional_coverage_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_directional_coverage_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "haat_calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="directional_coverage_analyses",
                        to="rf_analysis.haatcalculation",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="directional_coverage_analyses",
                        to="incidents.incident",
                    ),
                ),
                (
                    "infrastructure_rf_input_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="infrastructure_directional_analyses",
                        to="rf_analysis.rfanalysisinputsnapshot",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="directional_coverage_analyses",
                        to="sites.radiosite",
                    ),
                ),
                (
                    "subscriber_rf_input_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriber_directional_analyses",
                        to="rf_analysis.rfanalysisinputsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "site", "status"],
                        name="rf_dir_inc_site_status_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approved_at__isnull", True),
                                ("approved_by__isnull", True),
                                ("status", "draft"),
                            ),
                            models.Q(
                                ("approved_at__isnull", False),
                                ("approved_by__isnull", False),
                                ("status", "approved"),
                            ),
                            _connector="OR",
                        ),
                        name="rf_dir_approval_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("calculation_state", "complete"),
                                ("probable_two_way_distance_m__isnull", False),
                                ("talk_in_distance_m__isnull", False),
                                ("talk_out_distance_m__isnull", False),
                            ),
                            models.Q(
                                ("calculation_state__in", ["unsupported", "no_overlap"]),
                                ("probable_two_way_distance_m__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="rf_dir_distance_state_consistent",
                    ),
                ],
            },
        ),
    ]
