# Generated by Django 5.2.16 on 2026-07-28 16:13

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("rf_analysis", "0004_directionalcoverageanalysis_and_profile_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "calculation_state",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("insufficient_data", "Insufficient data"),
                        ],
                        max_length=24,
                    ),
                ),
                ("algorithm", models.CharField(max_length=120)),
                ("algorithm_version", models.CharField(max_length=120)),
                ("parameters", models.JSONField()),
                ("baseline_preset", models.CharField(max_length=80)),
                ("baseline_preset_version", models.CharField(max_length=80)),
                ("observation_snapshot", models.JSONField()),
                ("observation_sha256", models.CharField(max_length=64)),
                ("recommended_preset", models.JSONField()),
                ("before_after", models.JSONField()),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("result_snapshot", models.JSONField()),
                ("result_sha256", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_calibration_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_calibration_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calibration_sets",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["incident", "name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="FieldObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("good", "Good communications"),
                            ("marginal", "Marginal communications"),
                            ("failed", "Failed communications"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("measured", "Measured value"),
                            ("operator", "Operator judgment"),
                            ("imported", "Imported record"),
                            ("modeled", "Modeled value"),
                        ],
                        max_length=12,
                    ),
                ),
                ("observed_from", models.DateTimeField()),
                ("observed_to", models.DateTimeField()),
                (
                    "location_precision",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("generalized", "Generalized"),
                            ("redacted", "Redacted"),
                        ],
                        max_length=12,
                    ),
                ),
                ("coordinate_reference", models.CharField(default="EPSG:4326", max_length=32)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "location_precision_m",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                (
                    "direction_degrees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("359.999")),
                        ],
                    ),
                ),
                (
                    "path_distance_m",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                ("observer_source", models.CharField(max_length=160)),
                ("collection_method", models.CharField(max_length=120)),
                ("environment", models.JSONField(blank=True, default=dict)),
                ("measurements", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("quality_flags", models.JSONField(blank=True, default=list)),
                ("source_record_id", models.CharField(blank=True, max_length=160)),
                ("source_revision", models.CharField(max_length=160)),
                ("input_snapshot", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coverage_estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_observations",
                        to="rf_analysis.coverageestimate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_field_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "directional_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_observations",
                        to="rf_analysis.directionalcoverageanalysis",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_observations",
                        to="incidents.incident",
                    ),
                ),
                (
                    "infrastructure_rf_input_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="infrastructure_field_observations",
                        to="rf_analysis.rfanalysisinputsnapshot",
                    ),
                ),
                (
                    "subscriber_rf_input_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriber_field_observations",
                        to="rf_analysis.rfanalysisinputsnapshot",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="rf_analysis.fieldobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_to", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalibrationSetObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("observation_sha256", models.CharField(max_length=64)),
                ("review_evidence_sha256", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField()),
                (
                    "calibration_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observation_links",
                        to="rf_analysis.calibrationset",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calibration_links",
                        to="rf_analysis.fieldobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["calibration_set", "position"],
            },
        ),
        migrations.AddField(
            model_name="calibrationset",
            name="observations",
            field=models.ManyToManyField(
                related_name="calibration_sets",
                through="rf_analysis.CalibrationSetObservation",
                to="rf_analysis.fieldobservation",
            ),
        ),
        migrations.CreateModel(
            name="FieldObservationReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("excluded", "Excluded")], max_length=12
                    ),
                ),
                ("reason", models.TextField()),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="rf_analysis.fieldobservation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_observation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["observation", "created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="fieldobservation",
            index=models.Index(
                fields=["incident", "classification", "evidence_type"],
                name="rf_obs_inc_class_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldobservation",
            index=models.Index(fields=["incident", "observed_to"], name="rf_obs_inc_observed_idx"),
        ),
        migrations.AddConstraint(
            model_name="fieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("observed_to__gte", models.F("observed_from"))),
                name="rf_obs_window_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("latitude__isnull", True),
                        ("location_precision", "redacted"),
                        ("location_precision_m__isnull", True),
                        ("longitude__isnull", True),
                    ),
                    models.Q(
                        ("latitude__isnull", False),
                        ("location_precision__in", ["exact", "generalized"]),
                        ("location_precision_m__isnull", False),
                        ("longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="rf_obs_location_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="calibrationsetobservation",
            constraint=models.UniqueConstraint(
                fields=("calibration_set", "observation"), name="rf_calibration_observation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="calibrationsetobservation",
            constraint=models.UniqueConstraint(
                fields=("calibration_set", "position"), name="rf_calibration_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="calibrationset",
            constraint=models.UniqueConstraint(
                fields=("incident", "name", "version"), name="rf_calibration_name_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="calibrationset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True),
                        ("approved_by__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("approved_by__isnull", False),
                        ("status", "approved"),
                    ),
                    _connector="OR",
                ),
                name="rf_calibration_approval_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldobservationreview",
            index=models.Index(
                fields=["observation", "created_at"], name="rf_obs_review_history_idx"
            ),
        ),
    ]
