# Generated by Django 5.2.16 on 2026-07-28 20:20

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_operationalperiod_updated_at_incidentmembership"),
        ("rf_analysis", "0006_phase2validationbundle"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TerrainAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=120)),
                ("provider_version", models.CharField(max_length=120)),
                ("dataset_product", models.CharField(max_length=240)),
                ("dataset_version", models.CharField(max_length=160)),
                ("engine", models.CharField(max_length=120)),
                ("engine_version", models.CharField(max_length=120)),
                ("app_version", models.CharField(max_length=80)),
                (
                    "azimuth_deg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("359.999")),
                        ],
                    ),
                ),
                (
                    "maximum_distance_m",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500000),
                        ]
                    ),
                ),
                (
                    "sample_interval_m",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                (
                    "receiver_height_m",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1000")),
                        ],
                    ),
                ),
                (
                    "clearance_m",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1000")),
                        ],
                    ),
                ),
                (
                    "job_state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                (
                    "analysis_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("unsupported", "Unsupported"),
                        ],
                        max_length=16,
                    ),
                ),
                ("progress_step", models.CharField(default="queued", max_length=80)),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("input_snapshot", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                ("result_snapshot", models.JSONField(blank=True, default=dict)),
                ("result_sha256", models.CharField(blank=True, max_length=64)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_terrain_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coverage_estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terrain_analyses",
                        to="rf_analysis.coverageestimate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_terrain_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terrain_analyses",
                        to="incidents.incident",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terrain_analyses",
                        to="sites.radiosite",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retries",
                        to="rf_analysis.terrainanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["incident", "job_state"], name="rf_terrain_inc_state_idx"),
                    models.Index(fields=["incident", "status"], name="rf_terrain_inc_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approved_at__isnull", True),
                                ("approved_by__isnull", True),
                                ("status", "draft"),
                            ),
                            models.Q(
                                ("approved_at__isnull", False),
                                ("approved_by__isnull", False),
                                ("status", "approved"),
                            ),
                            _connector="OR",
                        ),
                        name="rf_terrain_approval_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("job_state", "queued"),
                                ("progress_percent", 0),
                                ("started_at__isnull", True),
                            ),
                            models.Q(
                                ("completed_at__isnull", True),
                                ("job_state", "running"),
                                ("started_at__isnull", False),
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("job_state__in", ["complete", "failed", "cancelled"]),
                            ),
                            _connector="OR",
                        ),
                        name="rf_terrain_job_state_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("analysis_state__in", ["complete", "partial", "unsupported"]),
                                ("job_state", "complete"),
                                models.Q(("result_sha256", ""), _negated=True),
                            ),
                            models.Q(("job_state", "complete"), _negated=True),
                            _connector="OR",
                        ),
                        name="rf_terrain_complete_has_result",
                    ),
                ],
            },
        ),
    ]
